src/Entity/Gutschein.php
<?php

namespace App\Entity;

use App\Repository\GutscheinRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GutscheinRepository::class)
 */
class Gutschein
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gs_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $gs_betrag;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $gs_bemerkung;

    /**
     * @ORM\Column(type="date")
     */
    private $gs_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="gutscheine")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPayed;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $gs_nummer;

    /**
     * @ORM\Column(type="integer")
     */
    private $kurstyp;

    /**
     * Gutschein constructor.
     */
    public function __construct()
    {
        $this->isPayed = false;
        $date = new DateTime();
        $this->hash = hash('md5', $date->format('d.m.Y # H:i'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGsName(): ?string
    {
        return $this->gs_name;
    }

    public function setGsName(string $gs_name): self
    {
        $this->gs_name = $gs_name;

        return $this;
    }

    public function getGsBetrag(): ?int
    {
        return $this->gs_betrag;
    }

    public function setGsBetrag(int $gs_betrag): self
    {
        $this->gs_betrag = $gs_betrag;

        return $this;
    }

    public function getGsBemerkung(): ?string
    {
        return $this->gs_bemerkung;
    }

    public function setGsBemerkung(?string $gs_bemerkung): self
    {
        $this->gs_bemerkung = $gs_bemerkung;

        return $this;
    }

    public function getGsDate(): ?DateTimeInterface
    {
        return $this->gs_date;
    }

    public function setGsDate(DateTimeInterface $gs_date): self
    {
        $this->gs_date = $gs_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsPayed(): ?bool
    {
        return $this->isPayed;
    }

    public function setIsPayed(bool $isPayed): self
    {
        $this->isPayed = $isPayed;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getGsNummer(): ?string
    {
        return $this->gs_nummer;
    }

    public function setGsNummer(string $gs_nummer): self
    {
        $this->gs_nummer = $gs_nummer;

        return $this;
    }

    public function getKurstyp(): ?int
    {
        return $this->kurstyp;
    }

    public function getKursTypName(): string
    {
        switch ($this->kurstyp){
            case 1:
                return 'Betrag';
            case 2:
                return 'Kitesurf-Grundkurs';
            case 3:
                return 'Kitesurf-Schnupperkurs';
            case 4:
                return 'Kitesurf-Aufsteigerkurs';
            case 6:
                return 'Wingsurf-Aufsteigerkurs';
            case 5:
                return 'Wingsurf-Grundkurs';
            case 7:
                return '3h Kitetraining';
            default:
                return 'null';
        }
    }

    public function setKurstyp(int $kurstyp): self
    {
        $this->kurstyp = $kurstyp;

        return $this;
    }

    public function getUrlString(): string
    {
        switch ($this->getKurstyp()){
            case 2:
            case 3:
            case 4:
            case 7:
                return 'www.ilovekitesurf-sylt.com';
            case 5:
            case 6:
                return 'www.ilovewingsurf-sylt.com';
        }

        return '';
    }
}

src/Form/GutscheinType.php
<?php

namespace App\Form;

use App\Entity\Gutschein;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GutscheinType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'gs_name',
            TextType::class,
            array(
                'label'    => "Name",
                'required' => true,
                'attr'     => ['maxlength' => 20],
                'row_attr' => [
                    'class' => 'myclass',
                    'placeholder' => 'interner Name - wird nicht gedruckt'
                ],
            )
        )->add(
            'gs_betrag',
            IntegerType::class,
            array(
                'label'    => "Betrag",
                'required' => true,
                'row_attr' => [
                    'placeholder' => 'Betrag in Cent'
                ],
            )
        )->add(
            'gs_nummer',
            HiddenType::class,
            array(
                'label'    => "Gutscheinnummer",
                'required' => true,
                'empty_data' => date("y").'-'.dechex(time()),
                'attr'     => ['maxlength' => 20],
            )
        )->add(
            'kurstyp',
            ChoiceType::class,
            [
                'choices' => [
                    'Betrag - Kite'        => 1,
                    'Betrag - Wing in Planung'        => 0,
                    'Kitesurf-Schnupperkurs' => 3,
                    '3h Kitesurftraining' => 7,
                    'Kitesurf-Grundkurs'     => 2,
                    'Kitesurf-Aufsteigerkurs'     => 4,
                    'Wingsurf-Grundkurs'     => 5,
                    'Wingsurf-Aufsteigerkurs'     => 6,
                ],
                'group_by' => function ($choice, $key, $value) {

                    if ($choice === 1 || $choice === 0) {
                        return 'Betrag';
                    }
                    if ($choice <= 4 || $choice === 7) {
                        return 'Kitesurfen';
                    }

                    return 'Wingsurfen';
                },
                'placeholder' => 'Gutschein wählen',
            ]
        )->add(
                'gs_bemerkung',
                TextareaType::class,
                array(
                    'required' => false,
                    'label' => "Bemerkung (intern)"
                )
            )->add(
                'gs_date',
                DateType::class,
                [
                    'label'        => "Ausstellungsdatum",
                    'widget'       => 'single_text',
                    'html5'        => false,
                    'input_format' => 'dd.mm.yyyy',
                    'format'       => 'dd.MM.yyyy',
                    // adds a class that can be selected in JavaScript
                    'attr'         => ['class' => 'js-datepicker'],
                ]
            )->add(
                'isPayed',
                CheckboxType::class,
                [
                    'label_attr' => ['class' => 'switch-custom'],
                    'required' => false,
                ]
            )->add(
                'hash',
                HiddenType::class,
                array(
                    'data' => dechex(time()).'-'.bin2hex(random_bytes(10)),
                )
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => Gutschein::class,
            ]
        );
    }
}

src/Controller/GutscheinController.php
<?php

namespace App\Controller;

use App\Entity\Gutschein;
use App\Form\GutscheinType;
use App\Repository\GutscheinRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/gutschein")
 * @IsGranted("ROLE_USER")
 */
class GutscheinController extends AbstractController
{
    /**
     * @Route("/", name="gutschein_index", methods={"GET"})
     */
    public function index(GutscheinRepository $gutscheinRepository): Response
    {
        $allGutscheine = $gutscheinRepository->findAll();
        $sum = 0;
        foreach ($allGutscheine as $gutschein) {
            $sum += $gutschein->getGsBetrag();
        }
        return $this->render('gutschein/index.html.twig', [
            'gutscheins' => $allGutscheine,
            'sum' => $sum,
        ]);
    }

    /**
     * @Route("/new", name="gutschein_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $gutschein = new Gutschein();
        $gutschein->setUser($this->getUser());
        $form = $this->createForm(GutscheinType::class, $gutschein);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($gutschein);
            $entityManager->flush();

            return $this->redirectToRoute('gutschein_index');
        }

        return $this->render('gutschein/new.html.twig', [
            'gutschein' => $gutschein,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="gutschein_show", methods={"GET"})
     */
    public function show(Gutschein $gutschein): Response
    {
        return $this->render('gutschein/show.html.twig', [
            'gutschein' => $gutschein,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="gutschein_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Gutschein $gutschein): Response
    {
        $form = $this->createForm(GutscheinType::class, $gutschein);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('gutschein_index');
        }

        return $this->render('gutschein/edit.html.twig', [
            'gutschein' => $gutschein,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="gutschein_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Gutschein $gutschein): Response
    {
        if ($this->isCsrfTokenValid('delete'.$gutschein->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($gutschein);
            $entityManager->flush();
        }

        return $this->redirectToRoute('gutschein_index');
    }
}

templates/gutschein/_delete_form.html.twig
<form method="post" action="{{ path('gutschein_delete', {'id': gutschein.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ gutschein.id) }}">
    <button class="btn btn-danger">Löschen</button>
</form>

templates/gutschein/_form.html.twig
{{ form_start(form, {'attr': {'class': 'foo'}}) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">Speichern</button>
{{ form_end(form) }}

templates/gutschein/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Gutschein{% endblock %}

{% block body %}
    <h1>Edit Gutschein</h1>

    {{ include('gutschein/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('gutschein_index') }}">zurück zur Liste</a>

    {{ include('gutschein/_delete_form.html.twig') }}
{% endblock %}

templates/gutschein/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gutschein index{% endblock %}

{% block body %}
    <h1>Gutscheine</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Nummer</th>
                <th class="d-none d-sm-table-cell">Betrag</th>
                <th>Typ</th>
                <th class="d-none d-md-table-cell">Datum</th>
                <th class="d-none d-sm-table-cell">Bezahlt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for gutschein in gutscheins %}
            <tr>
                <td><a href="{{ path('gutschein_show', {'id': gutschein.id}) }}">{{ gutschein.gsName }}</a></td>
                <td>{{ gutschein.gsnummer }}</td>
                <td class="d-none d-sm-table-cell">{{ gutschein.gsBetrag | number_format(2, ',', '0')  }}€</td>
                <td>{{ gutschein.KursTypName }}</td>
                <td class="d-none d-md-table-cell">{{ gutschein.gsDate ? gutschein.gsDate|date('d.m.Y') : '' }}</td>
                <td class="d-none d-sm-table-cell">{{ gutschein.isPayed ? 'Ja' : 'Nein' }}</td>
                <td>
                    <a href="{{ path('gutschein_edit', {'id': gutschein.id}) }}"><i class="fas fa-edit"></i></a>
                    <a target="_blank" href="{{ path('gutschein_pdf_hash', {'hash': gutschein.hash}) }}"><i class="fas fa-print"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Keine Gutscheine gefunden</td>
            </tr>
        {% endfor %}
        <tr><td></td><td><strong>{{ sum  | number_format(2, ',', '.')  }}€</strong></td></tr>
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('gutschein_new') }}">Neuer Gutschein</a>
{% endblock %}

templates/gutschein/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Neuer Gutschein{% endblock %}

{% block body %}
    <h1>Neuer Gutschein</h1>

    {{ include('gutschein/_form.html.twig') }}

    <a href="{{ path('gutschein_index') }}">zurück zur Liste</a>
{% endblock %}

templates/gutschein/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gutschein{% endblock %}

{% block body %}
    <h1>Gutschein</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ gutschein.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ gutschein.gsName }}</td>
            </tr>
            <tr>
                <th>GutscheinTyp</th>
                <td>{{ gutschein.KursTypName }}</td>
            </tr>
            <tr>
                <th>Betrag</th>
                <td>{{ gutschein.gsBetrag }}</td>
            </tr>
            <tr>
                <th>Bemerkung (intern)</th>
                <td>{{ gutschein.gsBemerkung }}</td>
            </tr>
            <tr>
                <th>Datum</th>
                <td>{{ gutschein.gsDate ? gutschein.gsDate|date('d.m.Y') : '' }}</td>
            </tr>
            <tr>
                <th>Ist Bezahlt</th>
                <td>{{ gutschein.isPayed ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Hash</th>
                <td>{{ gutschein.hash }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('gutschein_index') }}">zurück zur Liste</a>

    <a class="btn btn-warning" href="{{ path('gutschein_edit', {'id': gutschein.id}) }}">Ändern</a>

    {{ include('gutschein/_delete_form.html.twig') }}
{% endblock %}